/**
 * Turning two .ttf files into the committed glyph table — the pure half of
 * scripts/build_kot_glyph_atlas.ts, which is the command-line wrapper round it.
 *
 * SPLIT IN TWO SO THE DRIFT TEST CAN IMPORT IT. jest-tests/kot_raster.test.ts
 * rebuilds the atlas in memory and fails if the committed kot_glyph_atlas.ts
 * differs by a single dot, which is what stops the table and the script that
 * makes it from ever parting company. ts-jest compiles a test to CommonJS,
 * where `import.meta.url` is not allowed — so the font directory is a PARAMETER
 * here, and only the wrapper resolves it from its own location.
 *
 * DEV TIME ONLY. Nothing under the running server may import this file or
 * scripts/kot_ttf.ts; the same test reads the source tree and enforces it.
 */
import { join } from "node:path";
import { parseTtf, rasterizeGlyph, type ParsedFont } from "./kot_ttf.js";

/**
 * The only faces that exist: a size in printer dots per em, and the weights it
 * is baked in.
 *
 * BODY SIZES, in both weights (a dish name is bold, everything else is not):
 *   80mm (576 dots)  small 24, standard 28, large 34
 *   58mm (384 dots)  small 22, standard 24, large 28
 * BANNER SIZES, bold only — REPRINT and CANCELLED at 1.4x the body, rounded,
 * and never set in any other weight (escpos.ts kotRunFace):
 *   80mm  34, 39, 48          58mm  31, 34, 39
 * A size that is both (34, 28 → 39) is baked once, in every weight either use
 * needs.
 *
 * They are `KOT_BODY_PPEM` / `kotAtlasFaces()` in escpos.ts, spelled out here
 * because this script must be runnable before the atlas it generates exists —
 * and kot_raster.test.ts asserts this list IS kotAtlasFaces(), so a new size
 * cannot ship without its faces and a dropped size cannot leave its faces
 * behind as dead weight in the server's bundle.
 */
export const KOT_ATLAS_FACES: readonly { ppem: number; weights: readonly ("r" | "b")[] }[] = [
  { ppem: 22, weights: ["r", "b"] },
  { ppem: 24, weights: ["r", "b"] },
  { ppem: 28, weights: ["r", "b"] },
  { ppem: 31, weights: ["b"] },
  { ppem: 34, weights: ["r", "b"] },
  { ppem: 39, weights: ["b"] },
  { ppem: 48, weights: ["b"] },
];

/** ASCII only: everything else is folded to '?' by asciiSafe before it is set. */
export const FIRST_CHAR = 32;
export const LAST_CHAR = 126;

export interface BuiltGlyph {
  /** Advance in 1/16 dot — sixteenths, so a pen position never rounds twice. */
  a: number;
  /** Ink box offset from the pen, and its height above the baseline. */
  l: number;
  t: number;
  w: number;
  h: number;
  /** base64 of a row-major 1bpp bitmap, MSB first, stride = ceil(w / 8). */
  d: string;
}
export interface BuiltFace {
  ppem: number;
  weight: number;
  /** Tallest ink above, and deepest below, the baseline anywhere in the face. */
  top: number;
  bottom: number;
  g: Record<number, BuiltGlyph>;
}
export type BuiltAtlas = Record<string, BuiltFace>;

function buildFace(font: ParsedFont, ppem: number, weight: number): BuiltFace {
  const g: Record<number, BuiltGlyph> = {};
  let top = 0;
  let bottom = 0;
  for (let c = FIRST_CHAR; c <= LAST_CHAR; c++) {
    const gid = font.cmap.get(c) ?? 0;
    // Sixteenths of a dot. A whole-dot advance would round every glyph
    // independently and a 40-character line would drift several dots wide.
    const a = Math.round((font.adv[gid] ?? 0) * ppem * 16 / font.unitsPerEm);
    const bm = rasterizeGlyph(font, gid, ppem);
    g[c] = { a, l: bm.left, t: bm.top, w: bm.w, h: bm.h, d: bm.bits.toString("base64") };
    if (bm.h > 0) {
      if (bm.top > top) { top = bm.top; }
      if (bm.h - bm.top > bottom) { bottom = bm.h - bm.top; }
    }
  }
  return { ppem, weight, top, bottom, g };
}

/** The whole atlas, keyed "<ppem>r" / "<ppem>b". */
export function buildKotGlyphAtlas(fontDir: string): BuiltAtlas {
  const fonts = {
    r: parseTtf(join(fontDir, "LiberationSans-Regular.ttf")),
    b: parseTtf(join(fontDir, "LiberationSans-Bold.ttf")),
  };
  const atlas: BuiltAtlas = {};
  for (const { ppem, weights } of [...KOT_ATLAS_FACES].sort((x, y) => x.ppem - y.ppem)) {
    for (const key of (["r", "b"] as const).filter((w) => weights.includes(w))) {
      atlas[`${ppem}${key}`] = buildFace(fonts[key], ppem, key === "b" ? 700 : 400);
    }
  }
  return atlas;
}

/** The generated module, as text. Deterministic: same atlas, same string. */
export function atlasToModule(atlas: BuiltAtlas): string {
  const out: string[] = [];
  out.push("// GENERATED by scripts/build_kot_glyph_atlas.ts — DO NOT EDIT BY HAND.");
  out.push("//");
  out.push("// Liberation Sans 2.1.5 (SIL Open Font License 1.1), metric-compatible with");
  out.push("// Arial, pre-rendered to 1-bit printer dots. This table is the ONLY thing the");
  out.push("// KOT raster renderer knows about type: no font file and no font parser is");
  out.push("// reachable from the running server, so a docket's bytes are identical on a");
  out.push("// developer's Windows box, in CI and on the Debian VPS.");
  out.push("//");
  out.push("// Faces are keyed \"<dots per em><r|b>\". Per glyph: `a` is the advance in");
  out.push("// SIXTEENTHS of a dot, `l`/`t` the ink box's offset from the pen and its height");
  out.push("// above the baseline, `w`/`h` its size, and `d` a base64 row-major 1bpp bitmap");
  out.push("// (MSB first, stride = ceil(w / 8)). A blank glyph (space) has w = h = 0.");
  out.push("");
  out.push("export interface KotGlyph { a: number; l: number; t: number; w: number; h: number; d: string }");
  out.push("export interface KotFace {");
  out.push("  ppem: number;");
  out.push("  weight: number;");
  out.push("  /** Tallest ink above, and deepest below, the baseline anywhere in the face. */");
  out.push("  top: number;");
  out.push("  bottom: number;");
  out.push("  g: Record<number, KotGlyph>;");
  out.push("}");
  out.push("");
  out.push("export const KOT_ATLAS: Record<string, KotFace> = {");
  for (const [key, face] of Object.entries(atlas)) {
    out.push(`  ${JSON.stringify(key)}: { ppem: ${face.ppem}, weight: ${face.weight}, top: ${face.top}, bottom: ${face.bottom}, g: {`);
    for (const [code, glyph] of Object.entries(face.g)) {
      out.push(`    ${code}: { a: ${glyph.a}, l: ${glyph.l}, t: ${glyph.t}, w: ${glyph.w}, h: ${glyph.h}, d: ${JSON.stringify(glyph.d)} },`);
    }
    out.push("  } },");
  }
  out.push("};");
  return out.join("\n") + "\n";
}
